import type {Work} from './types';

/** Immutable starter data adapted from HolocronArchive_Latest/data/works.json. D1 remains the runtime source of truth. */
export const INITIAL_WORKS:Work[]=[
  {id:'a-new-hope',title:'스타워즈: 새로운 희망',originalTitle:'Star Wars: A New Hope (Episode IV)',type:'영화',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/EP4_POS_2_D-RESIZED_f977074a.jpeg',releaseDate:'1977-05-25',releasePrecision:'day',officialUrl:'https://www.starwars.com/films/star-wars-episode-iv-a-new-hope',franchise:'star-wars'},
  {id:'empire-strikes-back',title:'스타워즈: 제국의 역습',originalTitle:'Star Wars: The Empire Strikes Back (Episode V)',type:'영화',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/image_ca7910bd.jpeg',releaseDate:'1980-05-21',releasePrecision:'day',officialUrl:'https://www.starwars.com/films/star-wars-episode-v-the-empire-strikes-back',franchise:'star-wars'},
  {id:'return-of-the-jedi',title:'스타워즈: 제다이의 귀환',originalTitle:'Star Wars: Return of the Jedi (Episode VI)',type:'영화',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/EP6_POS_21_R-RESIZED_2873dc04.jpeg',releaseDate:'1983-05-25',releasePrecision:'day',officialUrl:'https://www.starwars.com/films/star-wars-episode-vi-return-of-the-jedi',franchise:'star-wars'},
  {id:'phantom-menace',title:'스타워즈: 보이지 않는 위험',originalTitle:'Star Wars: The Phantom Menace (Episode I)',type:'영화',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/EP1-IA-99993-RESIZED_f9ae99b6.jpeg',releaseDate:'1999-05-19',releasePrecision:'day',officialUrl:'https://www.starwars.com/films/star-wars-episode-i-the-phantom-menace',franchise:'star-wars'},
  {id:'clone-wars-series',title:'스타워즈: 클론 전쟁',originalTitle:'Star Wars: The Clone Wars',type:'애니메이션',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/the-clone-wars-poster-post-catalog_6fe148dd.jpeg',releaseDate:'2008-10-03',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/star-wars-the-clone-wars',franchise:'star-wars'},
  {id:'star-wars-rebels',title:'스타워즈 반란군',originalTitle:'Star Wars Rebels',type:'애니메이션',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/rebels-poster-post-catalog_ebbfc425.jpeg',releaseDate:'2014-10-03',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/star-wars-rebels',franchise:'star-wars'},
  {id:'rogue-one',title:'로그 원: 스타워즈 스토리',originalTitle:'Rogue One: A Star Wars Story',type:'영화',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/5adfd0618fdfb900016b5ca6-image_64bc2f8e.jpeg',releaseDate:'2016-12-16',releasePrecision:'day',officialUrl:'https://www.starwars.com/films/rogue-one',franchise:'star-wars'},
  {id:'mandalorian',title:'만달로리안',originalTitle:'The Mandalorian',type:'드라마',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/the-mandalorian-poster-post-catalog_1e7babb3.jpeg',releaseDate:'2019-11-12',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/the-mandalorian',franchise:'star-wars'},
  {id:'bad-batch',title:'스타워즈: 배드 배치',originalTitle:'Star Wars: The Bad Batch',type:'애니메이션',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/the-bad-batch-poster-post-catalog_31481d5a.jpeg',releaseDate:'2021-05-04',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/the-bad-batch',franchise:'star-wars'},
  {id:'andor',title:'안도르',originalTitle:'Andor',type:'드라마',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/andor-season-2-series-poster-catalog_be46f85f.jpeg',releaseDate:'2022-09-21',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/andor',franchise:'star-wars'},
  {id:'ahsoka',title:'아소카',originalTitle:'Ahsoka',type:'드라마',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/ahsoka-poster-post-catalog_3617795e.jpeg',releaseDate:'2023-08-22',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/ahsoka',franchise:'star-wars'},
  {id:'skeleton-crew',title:'스켈레톤 크루',originalTitle:'Skeleton Crew',type:'드라마',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/sw-skeleton-crew-series-poster-catalog-01_56b6c1c0.jpeg',releaseDate:'2024-12-02',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/star-wars-skeleton-crew',franchise:'star-wars'},
  {id:'tales-underworld',title:'스타워즈: 언더월드 이야기',originalTitle:'Star Wars: Tales of the Underworld',type:'애니메이션',status:'archive',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/totu-series-poster-catalog_971e1282.jpeg',releaseDate:'2025-05-04',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/tales-of-the-underworld',franchise:'star-wars'},
  {id:'maul-shadow-lord',title:'스타워즈: 몰 — 섀도 로드',originalTitle:'Star Wars: Maul - Shadow Lord',type:'애니메이션',status:'recent',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/star-wars-maul-shadow-lord-key-art-poster-now-streaming_7699ee99.jpeg',releaseDate:'2026-04-06',releasePrecision:'day',officialUrl:'https://www.starwars.com/series/star-wars-maul-shadow-lord',franchise:'star-wars'},
  {id:'mandalorian-grogu',title:'스타워즈: 만달로리안과 그로구',originalTitle:'Star Wars: The Mandalorian and Grogu',type:'영화',status:'recent',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/star-wars-the-mandalorian-and-grogu-key-art-poster_46aacf81.jpeg',releaseDate:'2026-05-22',releasePrecision:'day',officialUrl:'https://www.starwars.com/films/star-wars-the-mandalorian-and-grogu',franchise:'star-wars'},
  {id:'starfighter',title:'스타워즈: 스타파이터',originalTitle:'Star Wars: Starfighter',type:'영화',status:'upcoming',posterUrl:'https://lumiere-a.akamaihd.net/v1/images/sw-sop-featured-534jf84ks_2e2c554c.jpeg?region=0,0,1920,1080&width=960',releaseDate:'2027-05-28',releasePrecision:'day',officialUrl:'https://www.starwars.com/news/star-wars-starfighter-cast',franchise:'star-wars'},
];
