'use client';
import {useState, type CSSProperties} from 'react';
import {ArrowUpRight, Layers3, ShieldCheck, Orbit, Radio} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Article} from '@/lib/news';

export function Header({admin=false}:{admin?:boolean}) {
  return <header className="masthead"><a className="brand" href="/"><span className="brand-mark">H</span><span>HOLOCRON<small>THE GALAXY, ARCHIVED.</small></span></a><nav><a className={!admin?'active':''} href="/">뉴스 아카이브</a><span className="future">다음 은하계 <small>SOON</small></span></nav><a className="admin-link" href="/admin"><ShieldCheck size={16}/> 관리자 <ArrowUpRight size={14}/></a></header>;
}

const address=(url:string)=>{try{return new URL(url).hostname.replace(/^www\./,'')}catch{return url}};

export default function Newsroom({articles,initial}:{articles:Article[];initial:boolean}) {
  const [selected,setSelected]=useState<Article[]|null>(null);
  const cutoff=Date.now()-90*24*60*60*1000;
  const recent=articles.filter(a=>a.published&&Date.parse(a.published)>=cutoff);
  const grouped=Object.values(recent.reduce((r,a)=>{(r[a.topic]??=[]).push(a);return r;},{} as Record<string,Article[]>)).map(g=>g.sort((a,b)=>(a.published||'9999').localeCompare(b.published||'9999'))).sort((a,b)=>b[0].published.localeCompare(a[0].published));
  const sourceList=[{name:'StarWars.com',tag:'OFFICIAL',text:'루카스필름 공식 소식',url:'https://www.starwars.com/news',initial:'SW'},{name:'Star Wars News Net',tag:'FAN MEDIA',text:'팬의 시선으로 보는 은하계',url:'https://www.starwarsnewsnet.com',initial:'NN'},{name:'Collider',tag:'ENTERTAINMENT',text:'영화와 시리즈의 모든 것',url:'https://collider.com/tag/star-wars/',initial:'C'}];

  return <><Header/><main className="shell">
    <section className="intro"><div><div className="eyebrow"><span className="yellow-line"/> A TRANSMISSION FROM A GALAXY FAR, FAR AWAY</div><h1>은하계의 소식,<br className="mobile-break"/> <span>한곳에.</span></h1><p>공식 발표부터 새로운 이야기까지. 한국어로 만나는 스타워즈.</p></div><div className="sw-wordmark" aria-label="Star Wars">STAR<br/>WARS</div></section>
    <div className="archive-bar"><div><Orbit size={20}/><strong>스타워즈</strong><span className="edition">STAR WARS</span></div><span className="archive-count">최근 90일 · {grouped.length}개의 이야기 <span>·</span> 3개의 소스</span></div>
    <div className="content-layout"><section><div className="section-label"><h2>최신 소식 <span>LATEST TRANSMISSIONS</span></h2><span>최근 90일 · 게시일순</span></div>{initial&&<p className="initial-note">최근 90일 동안 확인된 기사입니다 · 관리자에서 새 소식을 수집할 수 있습니다.</p>}
      <div className="news-grid">{grouped.map((g,i)=>{const a=g[0];return <article className={`news-card ${g.length>1?'has-stack':''}`} key={a.topic}>
        {g.length>1&&<div className="source-stack" aria-label={`${g.length}개 출처`}><span className="stack-label"><Layers3 size={13}/> 중복 보도 {g.length}건</span>{g.slice(1).map((source,index)=><a key={source.id} href={source.url} target="_blank" rel="noreferrer" style={{'--stack-index':index} as CSSProperties} aria-label={`${source.source} 원문 열기`}><strong>{source.source}</strong><small>{address(source.url)}</small><ArrowUpRight size={14}/></a>)}</div>}
        <div className="main-card"><button className="image-button" onClick={()=>setSelected(g)} aria-label={`${a.title} 상세 보기`}>{a.image?<img src={a.image} alt={a.title} loading={i<2?'eager':'lazy'} referrerPolicy="no-referrer"/>:<span className="no-image">HOLOCRON ARCHIVE</span>}<span className="category">{a.category}</span>{a.id==="swnn-costume"&&<span className="related-image">관련 이미지 · StarWars.com</span>}{g.length>1&&<span className="group-count"><Layers3 size={13}/> {g.length}</span>}</button><div className="card-body"><div className="meta"><span className={a.source==='StarWars.com'?'official':''}>{a.source==='StarWars.com'&&<ShieldCheck size={12}/>} {a.source==='StarWars.com'?'공식':'뉴스'}</span><time>{a.published?a.published.slice(0,10).replaceAll('-','. '):'게시일 미확인'}</time></div><button className="title-button" onClick={()=>setSelected(g)}><h3>{a.title}</h3></button><p className="summary">{a.summary}</p><div className="card-bottom"><a href={a.url} target="_blank" rel="noreferrer"><span><strong>{a.source}</strong><small>{address(a.url)}</small></span><ArrowUpRight size={13}/></a>{g.length>1?<button onClick={()=>setSelected(g)}>모든 출처 보기</button>:<span>원문 보기</span>}</div></div></div>
      </article>})}</div>{!grouped.length&&<div className="empty">최근 90일 안에 공개된 기사가 없습니다. 관리자에서 새 소식을 수집해 주세요.</div>}<div className="end-mark"><span/>MAY THE FORCE BE WITH YOU<span/></div>
    </section><aside className="rail"><div className="rail-title"><Radio size={16}/><h2>뉴스 소스</h2><span>03</span></div><p className="rail-desc">서로 다른 시선, 하나의 이야기.</p>{sourceList.map(s=><a className="source-row" key={s.name} href={s.url} target="_blank" rel="noreferrer"><span className="source-logo">{s.initial}</span><span><small>{s.tag}</small><strong>{s.name}</strong><p>{s.text}</p></span><ArrowUpRight size={15}/></a>)}<div className="archive-explainer"><Layers3 size={24}/><h3>같은 소식은 하나로.</h3><p>중복된 보도를 한데 모았습니다. 확인된 게시 시각이 가장 이른 기사를 대표로, 다른 출처도 함께 읽어보세요.</p><span>카드 옆 출처에 마우스를 올려 펼쳐보세요.</span></div><div className="rail-foot">독립적인 팬 뉴스 아카이브<br/>Lucasfilm 및 Disney와 제휴하지 않습니다.</div></aside></div>
  </main><footer><a className="footer-brand" href="/">HOLOCRON</a><span>멀리, 저 멀리 은하계에서 온 이야기.</span><span>비공식 팬 프로젝트 · 기사와 이미지의 권리는 원저작자에게 있습니다.</span></footer>
  <Dialog open={!!selected} onOpenChange={v=>!v&&setSelected(null)}><DialogContent className="article-dialog">{selected&&<><DialogTitle>{selected[0].title}</DialogTitle><DialogDescription>기사 요약 및 관련 출처 · {selected[0].category}</DialogDescription>{selected[0].image&&<img className="dialog-image" src={selected[0].image} alt="기사 대표 이미지"/>}<p>{selected[0].summary}</p><h4>이 소식을 전한 매체</h4>{selected.map((a,i)=><a className="dialog-source" key={a.id} href={a.url} target="_blank" rel="noreferrer"><span><strong>{a.source}</strong><small>{address(a.url)} · {a.published?.replace('T',' ').slice(0,16)||'게시 시각 미확인'} {a.published?'UTC':''}</small></span><span>{i===0?'대표 출처':'관련 보도'} <ArrowUpRight size={15}/></span></a>)}<p className="small-muted">대표 출처는 수집한 기사 중 확인된 게시 시각을 기준으로 정합니다. 자세한 내용은 원문에서 확인해 주세요.</p></>}</DialogContent></Dialog></>;
}
