import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import ts from 'typescript';

async function pure(path){const source=await readFile(new URL(path,import.meta.url),'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(output).toString('base64')}`);}
const types=await pure('../lib/works/types.ts');
assert.equal(types.isWorkType('영화'),true,'movie is an allowed type');assert.equal(types.isWorkType('게임'),false,'games are not Phase 4 works');assert.equal(types.isWorkStatus('upcoming'),true,'upcoming is allowed');assert.equal(types.isWorkStatus('published'),false,'article statuses are not work statuses');assert.equal(types.formatReleaseDate('2027','year'),'2027년 공개','year precision does not invent a date');assert.equal(types.formatReleaseDate('2027-05','month'),'2027.05 공개','month precision does not invent a day');
const work=(id,status,releaseDate='2026-01-01')=>({id,title:id,originalTitle:id,type:'영화',status,posterUrl:'https://example.com/poster.jpg',releaseDate,releasePrecision:'day',officialUrl:null,franchise:'star-wars'});
const groups=types.groupWorksByStatus([work('later','upcoming','2027-09-01'),work('soon','upcoming','2027-01-01'),work('old','archive','1977-05-25'),work('newer','archive','2025-05-04'),work('recent','recent','2026-05-22')]);
assert.deepEqual(groups.upcoming.map(item=>item.id),['soon','later'],'upcoming works are ordered nearest first');assert.deepEqual(groups.archive.map(item=>item.id),['newer','old'],'archive works are ordered newest first');assert.equal(groups.recent[0].id,'recent','recent works render in their status group');
const schema=await readFile(new URL('../db/schema.ts',import.meta.url),'utf8');const migrationFiles=await readdir(new URL('../drizzle/',import.meta.url));const migration=await readFile(new URL(`../drizzle/${migrationFiles.find(file=>file.endsWith('.sql')&&file.startsWith('0003_'))}`,import.meta.url),'utf8');const repository=await readFile(new URL('../lib/works/repository.ts',import.meta.url),'utf8');const service=await readFile(new URL('../lib/works/service.ts',import.meta.url),'utf8');const publicPage=await readFile(new URL('../app/works/page.tsx',import.meta.url),'utf8');const adminPage=await readFile(new URL('../app/admin/works/page.tsx',import.meta.url),'utf8');const api=await readFile(new URL('../app/api/admin/works/route.ts',import.meta.url),'utf8');const card=await readFile(new URL('../components/works/work-card.tsx',import.meta.url),'utf8');const archive=await readFile(new URL('../components/works/works-archive.tsx',import.meta.url),'utf8');const newsroom=await readFile(new URL('../app/newsroom.tsx',import.meta.url),'utf8');
assert.match(schema,/export const works=sqliteTable/,'works is a dedicated D1 table');assert.match(migration,/CREATE TABLE `works`/,'works migration is present');assert.doesNotMatch(schema,/articles=.*works|works=.*articles/,'works are not added to articles');assert.match(repository,/update\(works\)\.set\(\{status\}\)/,'status updates target only works');assert.match(service,/isWorkStatus/,'invalid work status is rejected in domain service');assert.match(adminPage,/requireAdminSession/,'admin works page is session protected');assert.match(api,/getAdminSession/,'works mutation API is session protected');assert.match(api,/changeWorkStatus/,'works API stays thin and delegates service logic');assert.match(publicPage,/WorksArchive/,'public works route renders the archive');assert.match(newsroom,/href="\/works"/,'primary navigation links to works');assert.match(card,/onPointerEnter/,'desktop hover reveals work metadata');assert.match(card,/onKeyDown/,'keyboard users can reveal and dismiss metadata');assert.match(card,/onClick/,'mobile first tap reveals metadata without navigation');assert.match(card,/event\.key==='Escape'/,'Escape dismisses revealed metadata');assert.match(archive,/현재 공개 예정 작품이 없습니다/,'empty status groups render safely');
console.log('Works Archive: 24 assertions passed');
