import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import ts from 'typescript';

async function pure(path){const source=await readFile(new URL(path,import.meta.url),'utf8');const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;return import(`data:text/javascript;base64,${Buffer.from(output).toString('base64')}`);}
const types=await pure('../lib/works/types.ts');
const typesModule=`data:text/javascript;base64,${Buffer.from(ts.transpileModule(await readFile(new URL('../lib/works/types.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString('base64')}`;
const featuredSource=ts.transpileModule(await readFile(new URL('../lib/works/featured.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText.replace("'./types'",`'${typesModule}'`);
const featured=await import(`data:text/javascript;base64,${Buffer.from(featuredSource).toString('base64')}`);
const destinations=await pure('../lib/works/destination.ts');
const releaseDateInput=await pure('../lib/works/release-date-input.ts');
assert.equal(types.isWorkType('영화'),true,'movie is an allowed type');assert.equal(types.isWorkType('게임'),false,'games are not Phase 4 works');assert.equal(types.isWorkStatus('upcoming'),true,'upcoming is allowed');assert.equal(types.isWorkStatus('published'),false,'article statuses are not work statuses');assert.equal(types.formatReleaseDate('2027','year'),'2027년 공개','year precision does not invent a date');assert.equal(types.formatReleaseDate('2027-05','month'),'2027.05 공개','month precision does not invent a day');
assert.deepEqual(releaseDateInput.parseReleaseDate('2026-09-26'),{year:'2026',month:'09',day:'26'},'an existing exact date is split for editing');assert.deepEqual(releaseDateInput.parseReleaseDate('2026-09'),{year:'2026',month:'09',day:''},'an existing month date is split for editing');assert.deepEqual(releaseDateInput.parseReleaseDate('2026'),{year:'2026',month:'',day:''},'an existing year is split for editing');assert.equal(releaseDateInput.composeReleaseDate({year:'2026',month:'9',day:'6'},'day'),'2026-09-06','day precision composes a padded YYYY-MM-DD value');assert.equal(releaseDateInput.composeReleaseDate({year:'2026',month:'9',day:''},'month'),'2026-09','month precision composes YYYY-MM');assert.equal(releaseDateInput.composeReleaseDate({year:'2026',month:'',day:''},'year'),'2026','year precision stores YYYY');assert.equal(releaseDateInput.composeReleaseDate({year:'2026',month:'09',day:''},'day'),'','incomplete dates remain unsaved while each part stays in local state');assert.deepEqual(releaseDateInput.partsForPrecisionChange({year:'2026',month:'09',day:'26'},'month'),{year:'2026',month:'09',day:''},'day to month keeps year and month');assert.deepEqual(releaseDateInput.partsForPrecisionChange({year:'2026',month:'09',day:'26'},'year'),{year:'2026',month:'',day:''},'day to year keeps only year');assert.deepEqual(releaseDateInput.partsForPrecisionChange({year:'2026',month:'',day:''},'day'),{year:'2026',month:'',day:''},'year to day keeps year and asks for missing parts');assert.equal(releaseDateInput.composeReleaseDate({year:'2026',month:'09',day:'26'},'unknown'),'','unknown precision clears the stored date');assert.equal(releaseDateInput.isValidReleaseDateParts({year:'2026',month:'',day:''},'year'),true,'four-digit years are valid');assert.equal(releaseDateInput.isValidReleaseDateParts({year:'0000',month:'',day:''},'year'),false,'year zero is not a calendar date');assert.equal(releaseDateInput.isValidReleaseDateParts({year:'2026',month:'9',day:''},'month'),true,'months in range are valid');assert.equal(releaseDateInput.isValidReleaseDateParts({year:'2026',month:'13',day:''},'month'),false,'out-of-range months are rejected');assert.equal(releaseDateInput.isValidReleaseDateParts({year:'2024',month:'2',day:'29'},'day'),true,'leap day is accepted in a leap year');assert.equal(releaseDateInput.isValidReleaseDateParts({year:'2025',month:'2',day:'29'},'day'),false,'leap day is rejected in a non-leap year');assert.equal(releaseDateInput.isValidReleaseDateParts({year:'2026',month:'9',day:'31'},'day'),false,'days outside a month are rejected');assert.equal(releaseDateInput.sanitizeReleaseDatePart('2a0-2',4),'202','date parts accept digits only and respect their length');
const work=(id,status,releaseDate='2026-01-01')=>({id,title:id,originalTitle:id,type:'영화',status,posterUrl:'https://example.com/poster.jpg',releaseDate,releasePrecision:'day',officialUrl:null,franchise:'star-wars'});
const groups=types.groupWorksByStatus([work('later','upcoming','2027-09-01'),work('soon','upcoming','2027-01-01'),work('old','archive','1977-05-25'),work('newer','archive','2025-05-04'),work('recent','recent','2026-05-22')]);
assert.deepEqual(groups.upcoming.map(item=>item.id),['soon','later'],'upcoming works are ordered nearest first');assert.deepEqual(groups.archive.map(item=>item.id),['newer','old'],'archive works are ordered newest first');assert.equal(groups.recent[0].id,'recent','recent works render in their status group');
const featuredWorks=[work('recent-old','recent','2026-04-01'),work('recent-new','recent','2026-05-01'),work('upcoming-soon','upcoming','2027-01-01'),work('upcoming-later','upcoming','2027-07-01')];
assert.equal(featured.selectFeaturedWork(featuredWorks).id,'recent-new','the newest recent movie is featured deterministically');assert.equal(featured.selectFeaturedWork(featuredWorks.filter(item=>item.status!=='recent')).id,'upcoming-soon','nearest dated upcoming work is featured when there is no recent movie');assert.equal(featured.selectFeaturedWork([work('unknown','upcoming',null),work('dated','upcoming','2027-02-01')]).id,'dated','dated upcoming work wins over unknown date');assert.equal(featured.selectFeaturedWork([work('unknown-b','upcoming',null),work('unknown-a','upcoming',null)]).id,'unknown-a','unknown-date fallback is deterministic');assert.equal(featured.selectFeaturedWork([]),null,'empty catalog has no featured work');assert.equal(featured.selectFeaturedWork([work('archive','archive','2020-01-01')]),null,'archive-only catalog has no featured work');
assert.deepEqual(destinations.resolveWorkDestination({...work('official','upcoming'),officialUrl:'https://www.starwars.com/'}),{kind:'official',url:'https://www.starwars.com/'},'upcoming work uses its official URL');assert.deepEqual(destinations.resolveWorkDestination(work('unavailable','upcoming')),{kind:'unavailable'},'upcoming work without official URL is safely unavailable');assert.deepEqual(destinations.resolveWorkDestination(work('ticket','recent')),{kind:'ticket'},'recent movie opens ticket choice');assert.equal(destinations.resolveWorkDestination({...work('recent-drama','recent'),type:'드라마'}).kind,'disney-plus','recent non-movie uses Disney+');assert.equal(destinations.resolveWorkDestination({...work('archive-animation','archive'),type:'애니메이션'}).kind,'disney-plus','archive work uses Disney+');
const schema=await readFile(new URL('../db/schema.ts',import.meta.url),'utf8');const migrationFiles=await readdir(new URL('../drizzle/',import.meta.url));const migration=await readFile(new URL(`../drizzle/${migrationFiles.find(file=>file.endsWith('.sql')&&file.startsWith('0003_'))}`,import.meta.url),'utf8');const repository=await readFile(new URL('../lib/works/repository.ts',import.meta.url),'utf8');const service=await readFile(new URL('../lib/works/service.ts',import.meta.url),'utf8');const publicPage=await readFile(new URL('../app/works/page.tsx',import.meta.url),'utf8');const adminPage=await readFile(new URL('../app/admin/works/page.tsx',import.meta.url),'utf8');const api=await readFile(new URL('../app/api/admin/works/route.ts',import.meta.url),'utf8');const card=await readFile(new URL('../components/works/work-card.tsx',import.meta.url),'utf8');const archive=await readFile(new URL('../components/works/works-archive.tsx',import.meta.url),'utf8');const newsroom=await readFile(new URL('../app/newsroom.tsx',import.meta.url),'utf8');
assert.match(schema,/export const works=sqliteTable/,'works is a dedicated D1 table');assert.match(migration,/CREATE TABLE `works`/,'works migration is present');assert.doesNotMatch(schema,/articles=.*works|works=.*articles/,'works are not added to articles');assert.match(repository,/update\(works\)\.set\(\{status\}\)/,'status updates target only works');assert.match(service,/isWorkStatus/,'invalid work status is rejected in domain service');assert.match(adminPage,/requireAdminSession/,'admin works page is session protected');assert.match(api,/getAdminSession/,'works mutation API is session protected');assert.match(api,/changeWorkStatus/,'works API stays thin and delegates service logic');assert.match(publicPage,/WorksArchive/,'public works route renders the archive');assert.match(newsroom,/href="\/works"/,'primary navigation links to works');assert.match(card,/onPointerEnter/,'desktop hover reveals work metadata');assert.match(card,/onKeyDown/,'keyboard users can reveal and dismiss metadata');assert.match(card,/onClick/,'mobile first tap reveals metadata without navigation');assert.match(card,/event\.key==='Escape'/,'Escape dismisses revealed metadata');assert.match(archive,/현재 공개 예정 작품이 없습니다/,'empty status groups render safely');assert.match(archive,/기대작/,'works archive renders a featured projection');assert.match(archive,/resolveWorkDestination/,'normal and featured cards share the destination resolver');
const ticketDialog=await readFile(new URL('../components/works/work-destination-dialog.tsx',import.meta.url),'utf8');assert.match(ticketDialog,/CGV/,'ticket dialog includes CGV');assert.match(ticketDialog,/롯데시네마/,'ticket dialog includes Lotte Cinema');assert.match(ticketDialog,/메가박스/,'ticket dialog includes Megabox');assert.match(ticketDialog,/target="_blank"/,'ticket destinations preserve external-link behaviour');
const workForm=await readFile(new URL('../components/works/work-form.tsx',import.meta.url),'utf8');assert.doesNotMatch(workForm,/type=["']date["']/,'the form does not use the native date input');assert.match(workForm,/<label><small>연<\/small><input/,'the year has a separate labeled input');assert.match(workForm,/<label><small>월<\/small><input/,'the month has a separate labeled input');assert.match(workForm,/<label><small>일<\/small><input/,'the day has a separate labeled input');assert.match(workForm,/isValidReleaseDateParts\(dateParts,value\.releasePrecision\)/,'invalid calendar dates cannot be submitted');
console.log('Works Archive: 65 assertions passed');
